name: Publish

on:
  push:
    branches:
      - master
      - next

permissions:
  contents: write       # Allows Actions to push updates to the repository
  pull-requests: write  # Allows the bot to create or update pull requests if needed
  issues: write         # Allows the bot to create issues (e.g., for release notes)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run npm audit (optional)
        run: npm audit

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
